### ISSUE TITLE
RAM usage value inaccurate

### ISSUE THREAD

**Issue by aidenmitchell** [mesacarlos/WebConsole#19]
According to Task Manager on my server, It's not using as much as the web interface says. Is there a way to fix this?

**Comment by mesacarlos** [comment]
Hello again,
Thank you for pointing this out.

There isn't much that I can do to solve that problem. It is related with the way Java handles your PC memory. 
You can check more about this problem here: https://stackoverflow.com/questions/35539283/javas-ram-usage-doesnt-correspond-to-what-the-task-manager-says

WebConsole will read the "real" used memory by your server instance (like other plugins like Essentials do). Task Manager shows the amount of memory assigned to the Java VM at that moment.

**Comment by aidenmitchell** [comment]
Ok, so it's normal. Thanks.
