### ISSUE TITLE
Security Errors!

### ISSUE THREAD

**Issue by steevLP** [mesacarlos/WebConsole#2]
HI! I've installed The webconosole and configured it like it should be..
well.. it does nothing realy.. everything is 0/0 and it's throwing console errors like nothing else

these are all error I get when loading the Page

`WebConsoleConnector.js?v=1.4:23 Mixed Content: The page at 'https://panel.slpnetwork.de/#' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://91.218.65.98/'. This request has been blocked; this endpoint must be available over WSS.
connect @ WebConsoleConnector.js?v=1.4:23
loadConnection @ WebConsoleManager.js?v=1.4:34
openServer @ WebConsole.js?v=1.4:34
onclick @ (index):1
WebConsoleConnector.js?v=1.4:23 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at WebConsoleConnector.connect (https://panel.slpnetwork.de/scripts/WebConsoleConnector.js?v=1.4:23:20)
    at WebConsoleManager.loadConnection (https://panel.slpnetwork.de/scripts/WebConsoleManager.js?v=1.4:34:25)
    at openServer (https://panel.slpnetwork.de/scripts/WebConsole.js?v=1.4:34:20)
    at HTMLAnchorElement.onclick (https://panel.slpnetwork.de/#:1:1)
connect @ WebConsoleConnector.js?v=1.4:23
loadConnection @ WebConsoleManager.js?v=1.4:34
openServer @ WebConsole.js?v=1.4:34
onclick @ (index):1`

I hope this is helpfull to improve or fix theses issues

**Comment by mesacarlos** [comment]
That error occurs because you are loading your client over HTTPS, but you haven't configured SSL in your Minecraft server, and your browser is blocking that connection. Check your plugin configuration and enable SSL following this wiki page info:

https://github.com/mesacarlos/WebConsole/wiki/SSL-Configuration

Then, tick the 'SSL is enabled' checkbox in your client when re-adding your server and problem will be solved.
