### ISSUE TITLE
Impossible to connect [Bungeecord-paper]

### ISSUE THREAD

**Issue by Redstylt** [mesacarlos/WebConsole#27]
Hello, today I installed the plugin on my server1 (paper-334 | MC 1.15.2) of my Bungeecord network.
And I can't connect when I add the server on the web interface. After a ctrl+F5, it worked. But the other members of my staff never succeeded and now that I'm on my laptop it doesn't work either.
What's the problem?

PS : a suggestion: add buttons to start, restart, stop the server.

**Comment by mesacarlos** [comment]
Hello,
Where are you hosting your mc server? (VPS/dedicated or home)
What are you typing as host and port at config.yml (server side) and when adding the server in the web interface?

**Comment by Redstylt** [comment]
VPS : https://privateheberg.com/
The config file : https://imgur.com/a/ZfYIAh9
I made the keystore.jks in the webconsole folder
I have any error about webconsole in the minecraft console when i start the server

**Comment by mesacarlos** [comment]
I see that you made a selfsigned certificate. The problem is that your browser is blocking connections to your server because it thinks that the webpage is not secure. To avoid this follow this step:

> Then, to enable connections from your browser remember to first navigate to https://server_ip:8080/ (change server_ip with your server IP, and port if you changed it before at config.yml) and skip the security warning (Click on connect anyway). This is required in order to allow your browser to connect to servers using your own selfsigned certificate. If you don't follow this step, your browser will block connections to your WebSockets Server.

Your browser will stop trusting that certificate in some hours or days. If that happens repeat this process.

I only reccomend using that type of cert for testing purposes. I reccommend you switching to a valid cert like letsencrypt certs. Those are valid for 3 months and you can renew them for free.
You can obviously disable SSL encryption too if you dont need that extra security.
